-- ============================================
-- Departments
-- ============================================

INSERT INTO Departments (Name, Description)
VALUES
('HR', 'Human Resources'),
('IT', 'Information Technology'),
('Finance', 'Finance Department'),
('Admin', 'Administration Department'),
('Operations', 'Operations Department');



-- ============================================
-- Users
-- Note:
-- Passwords will be generated by the API
-- ============================================

INSERT INTO Users
(
    Username,
    Email,
    PasswordHash,
    Role
)
VALUES
(
    'admin',
    'admin@company.com',
    '$2a$11$TEMP_HASH',
    'Admin'
),
(
    'user',
    'user@company.com',
    '$2a$11$TEMP_HASH',
    'User'
);



-- ============================================
-- Employees
-- ============================================

INSERT INTO Employees
(
    Name,
    Email,
    Phone,
    Salary,
    DepartmentId,
    IsActive
)
VALUES
(
    'Aakash',
    'aakash@company.com',
    '9876543210',
    50000,
    2,
    1
),
(
    'Rahul',
    'rahul@company.com',
    '9876543211',
    45000,
    2,
    1
),
(
    'Priya',
    'priya@company.com',
    '9876543212',
    55000,
    1,
    1
),
(
    'Arun',
    'arun@company.com',
    '9876543213',
    60000,
    3,
    1
),
(
    'Kiran',
    'kiran@company.com',
    '9876543214',
    48000,
    4,
    1
),
(
    'Suresh',
    'suresh@company.com',
    '9876543215',
    52000,
    5,
    1
),
(
    'Meena',
    'meena@company.com',
    '9876543216',
    47000,
    1,
    1
),
(
    'Vijay',
    'vijay@company.com',
    '9876543217',
    65000,
    2,
    1
);